name: 'Setup Packer'
description: 'Sets up Packer CLI in your GitHub Actions workflow.'
author: 'HashiCorp, Inc. (Forked by Todd Niswonger)'
inputs:
  packer_version:
    description: 'The version of Packer CLI to install. A value of `latest` will install the latest version of Packer CLI. Defaults to `latest`.'
    default: 'latest'
    required: false
  packer_wrapper:
    description: 'Whether or not to install a wrapper to wrap subsequent calls of the `packer` binary and expose its STDOUT, STDERR, and exit code as outputs named `stdout`, `stderr`, and `exitcode` respectively. Defaults to `true`.'
    default: 'true'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'terminal'
  color: 'purple'
